- hosts: all
  become: yes
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Python pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker-compose
      pip:
        name: docker-compose
