name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and test
        run: |
          pip install -r requirements.txt
          pytest

      - name: Build Docker Image
        run: |
          docker build -t gabidelcea/my-flask-app:${{ github.sha }} .
          docker tag gabidelcea/my-flask-app:${{ github.sha }} gabidelcea/my-flask-app:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker push gabidelcea/my-flask-app:${{ github.sha }}
          docker push gabidelcea/my-flask-app:latest

  deploy-to-ec2:
    needs: build-and-test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull gabidelcea/my-flask-app:latest
            docker stop my-flask-app || true
            docker rm my-flask-app || true
            docker run -d --name my-flask-app -p 80:5000 -p 443:5000 \
              -v /etc/letsencrypt:/etc/letsencrypt:ro \
              gabidelcea/my-flask-app:latest
