name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies and test
        run: |
          pip install -r requirements.txt
          pytest

      - name: Build Docker Image
        run: |
          docker build -t gabidelcea/my-flask-app:${{ github.sha }} .
          docker tag gabidelcea/my-flask-app:${{ github.sha }} gabidelcea/my-flask-app:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push gabidelcea/my-flask-app:${{ github.sha }}
          docker push gabidelcea/my-flask-app:latest

  deploy-to-ec2:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Hostname
        run: echo "Connecting to host: ${{ secrets.EC2_HOST }}"

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Debug SSH Connection
        run: |
          ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} echo "SSH Connected!"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull gabidelcea/my-flask-app:latest
            docker stop my-flask-app || true
            docker rm my-flask-app || true
            docker run -d --name my-flask-app -p 80:5000 -p 443:5000 \
              -v /etc/letsencrypt:/etc/letsencrypt:ro \
              gabidelcea/my-flask-app:latest
