name: Deploy to AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    needs: CI - Code Checks and Build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster myCluster \
            --service myService \
            --force-new-deployment
