deploy-to-ec2:
  needs: code-check-and-build
  runs-on: ubuntu-latest

  steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker pull myrepo/myapp:latest
          docker stop my-flask-app || true
          docker rm my-flask-app || true
          docker run -d --name my-flask-app -p 80:5000 myrepo/myapp:latest
